#ifndef REBORN_UI_TOKENS_H
#define REBORN_UI_TOKENS_H

#define REBORN_SCREEN_W 480
#define REBORN_SCREEN_H 360

/* RGB hex values from the first Reborn concept */
#define REBORN_BG              0x090B0D
#define REBORN_BG_RAISED       0x101317
#define REBORN_SURFACE         0x15191E
#define REBORN_SURFACE_HOVER   0x1B2026
#define REBORN_SURFACE_BORDER  0x2A3037
#define REBORN_TEXT_PRIMARY    0xF2F1ED
#define REBORN_TEXT_SECONDARY  0xAAAEB5
#define REBORN_TEXT_MUTED      0x747A83
#define REBORN_ACCENT_GOLD     0xE6B965
#define REBORN_ACCENT_GOLD_HI  0xFFD17B
#define REBORN_FOCUS_GLOW      0xF5C973

#define REBORN_SPACE_XS 4
#define REBORN_SPACE_SM 8
#define REBORN_SPACE_MD 12
#define REBORN_SPACE_LG 16
#define REBORN_SPACE_XL 24

#define REBORN_RADIUS_SM 6
#define REBORN_RADIUS_MD 10
#define REBORN_RADIUS_LG 14

#define REBORN_STATUSBAR_H 30
#define REBORN_BOTTOMBAR_H 42
#define REBORN_MIN_ROW_H 44
#define REBORN_FOCUS_STROKE 2

#endif
