#!/usr/bin/env python3
"""Build bounded native atlases from the supplied SVG pack and public DejaVu 2.37.
Pass the extracted official dejavu-fonts-ttf-2.37 directory. No system fonts.
"""
import argparse, hashlib, io, json
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import cairosvg

ROOT = Path(__file__).resolve().parents[2]
p = argparse.ArgumentParser(description=__doc__)
p.add_argument('dejavu', type=Path)
a = p.parse_args()
font_file = a.dejavu / 'ttf/DejaVuSans.ttf'
font = ImageFont.truetype(str(font_file), 24)
chars = list(range(0x250)) + list(range(0x370, 0x500)) + [0x2026,0x2022,0x2013,0x2014,0x2190,0x2191,0x2192,0x2193,0xfffd]
atlas = Image.new('RGBA',(1024,1024))
d = ImageDraw.Draw(atlas)
adv = []
for i, cp in enumerate(chars):
 ch = chr(cp) if cp >= 32 else ' '
 x, y = i%32*32, i//32*32
 d.text((x+2,y+25),ch,font=font,fill='white',anchor='ls')
 adv.append(font.getlength(ch))
(ROOT/'assets/fonts/reborn-ui.rgba').write_bytes(atlas.tobytes())
lines = ['// Generated by tools/assets/build_atlas.py; DejaVu Sans 2.37, 24 px.',
 'pub const ADVANCE: &[f32] = &[' + ','.join(f'{x:.4f}' for x in adv) + '];',
 'pub fn index(ch: char) -> u16 { let n=ch as u32; match n { 0..=0x24f => if n<32 {32} else {n as u16}, 0x370..=0x4ff => (n-0x370+0x250) as u16,',
 ','.join(f'0x{cp:x} => {i}' for i,cp in enumerate(chars) if i>=992) + ', _ => 1000 } }']
(ROOT/'crates/reborn-ui/src/glyphs.rs').write_text('\n'.join(lines)+'\n')
# Stable slots retain the graphics ABI. Additional device-only symbols alias
# the closest supplied Simple SVG; no SVG parser is installed at runtime.
names=['albums','artist','back','battery','bluetooth','chevron_right','brightness','eq','eq','headphones','heart','menu','menu','menu','next','pause','play','previous','repeat','albums','settings','shuffle','songs','albums','volume','wifi']
icons=Image.new('RGBA',(192,160))
source=ROOT/'assets/icons/src'
hashes={}
for i,name in enumerate(names):
 raw=(source/(name+'.svg')).read_bytes();hashes[name]=hashlib.sha256(raw).hexdigest()
 (ROOT/'assets/icons/src'/ (name+'.svg')).write_bytes(raw)
 png=cairosvg.svg2png(bytestring=raw.replace(b'currentColor',b'white'),output_width=32,output_height=32)
 icons.paste(Image.open(io.BytesIO(png)),(i%6*32,i//6*32))
(ROOT/'assets/icons/reborn-icons.rgba').write_bytes(icons.tobytes())
(ROOT/'assets/fonts/provenance.json').write_text(json.dumps({'family':'DejaVu Sans','version':'2.37','source':'https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_2_37/dejavu-fonts-ttf-2.37.tar.bz2','ttf_sha256':hashlib.sha256(font_file.read_bytes()).hexdigest(),'atlas_size':[1024,1024],'cell':32,'font_px':24,'glyphs':len(chars),'runtime_font_files':False},indent=2)+'\n')
(ROOT/'assets/icons/provenance.json').write_text(json.dumps({'source':'Owner-supplied Reborn Y2 Simple UI Asset Pack','svg_sha256':hashes,'slots':names},indent=2)+'\n')
